### ISSUE TITLE
unexpected EOF when reading TTF

### ISSUE THREAD

**Issue by iangudger** [seehuhn/go-sfnt#1]
When parsing this font ([EmptyArial.ttf.zip](https://github.com/seehuhn/go-sfnt/files/12678085/EmptyArial.ttf.zip)) with `sfnt.Read`, I get the error `unexpected EOF`.

This is an invisible font which is useful for adding overlay text to a PDF. This font works with other software.

**Comment by seehuhn** [comment]
Thank you for your report.  The problem is that this font has an empty "GDEF" table.  I'll teach my library to treat an empty GDEF table the same as a missing GDEF table to work around this.
